//! Bundled polyphone phrase dictionary (gated behind the `polyphone-dict`
//! cargo feature). The phrase table itself is generated by `build.rs`.

include!(concat!(env!("OUT_DIR"), "/polyphone_phrases.rs"));
